main: io.github.enqorman.minefactions.MineFactionsPlugin
name: MineFactions
version: '1.0'
api-version: '1.20'
description: A Factions Plugin for Minecraft 1.20
author: enqorman
depend:
  - WorldGuard
  - PlaceholderAPI
commands:
  supersecretfactioncommand:
    usage: /<command>
    description: The Factions Command
    permission: minefactions.commands.faction
permissions:
  minefactions.commands.faction:
    description: The Command Usage permission for /faction